/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.glassfy;

import androidx.annotation.Nullable;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

import java.util.HashMap;

import io.glassfy.androidsdk.Glassfy;
import io.glassfy.androidsdk.GlassfyError;
import io.glassfy.androidsdk.OfferingsCallback;
import io.glassfy.androidsdk.SkuCallback;
import io.glassfy.androidsdk.model.Offering;
import io.glassfy.androidsdk.model.Offerings;
import io.glassfy.androidsdk.model.Sku;


@Kroll.module(name = "TiGlassfy", id = "ti.glassfy")
public class TiGlassfyModule extends KrollModule {

    // Standard Debugging variables
    private static final String LCAT = "TiGlassfyModule";

    public TiGlassfyModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    // Methods
    @Kroll.method
    public void initialize(String key) {
        Glassfy.initialize(TiApplication.getAppCurrentActivity(), key, false, null);
    }

    @Kroll.method
    public void getOfferings() {
        Glassfy.offerings(new OfferingsCallback() {
            @Override
            public void onResult(@Nullable Offerings offers, @Nullable GlassfyError err) {
                Offering offering = null;
                if (offers != null) {
                    for (Offering o : offers.getAll()) {
                        if (o.getOfferingId().equals("premium")) {
                            offering = o;
                        }
                    }
                }
                if (offering != null) {
                    KrollDict kdOffers = new KrollDict();
                    HashMap[] offerList = new HashMap[offering.getSkus().size()];
                    int i = 0;
                    for (Sku sku : offering.getSkus()) {
                        KrollDict kd = new KrollDict();
                        kd.put("title", sku.getProduct().getTitle());
                        kd.put("description", sku.getProduct().getDescription());
                        kd.put("price", sku.getProduct().getPrice());
                        // sku.getExtravars();
                        offerList[i] = kd;
                        ++i;
                    }
                    kdOffers.put("offers", offerList);
                    fireEvent("offerings", kdOffers);
                }
            }
        });
    }

    @Kroll.method
    public void getSku(String sku) {
        Glassfy.sku("premium_weekly", new SkuCallback() {
            @Override
            public void onResult(@Nullable Sku sku, @Nullable GlassfyError err) {
                if (sku != null) {
                    KrollDict kd = new KrollDict();
                    kd.put("title", sku.getProduct().getTitle());
                    kd.put("description", sku.getProduct().getDescription());
                    kd.put("price", sku.getProduct().getPrice());
                    // sku.getExtravars();
                    fireEvent("sku", kd);
                }
            }
        });
    }
}

